// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/execution": {
    params: {};
  };
  "/media-prices": {
    params: {};
  };
  "/quotations": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/service-visibility": {
    params: {};
  };
  "/service-risk": {
    params: {};
  };
  "/service-site-audit": {
    params: {};
  };
  "/service-pilot": {
    params: {};
  };
  "/formal-reports": {
    params: {};
  };
  "/sop": {
    params: {};
  };
  "/sop/projects/:projectPubId": {
    params: {
      "projectPubId": string;
    };
  };
  "/post-analysis": {
    params: {};
  };
  "/post-analysis/tasks/:taskPubId": {
    params: {
      "taskPubId": string;
    };
  };
  "/accounts": {
    params: {};
  };
  "/browsers": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/execution" | "/media-prices" | "/quotations" | "/onboarding" | "/service-visibility" | "/service-risk" | "/service-site-audit" | "/service-pilot" | "/formal-reports" | "/sop" | "/sop/projects/:projectPubId" | "/post-analysis" | "/post-analysis/tasks/:taskPubId" | "/accounts" | "/browsers";
  };
  "shell.tsx": {
    id: "shell";
    page: "/";
  };
  "features/login/route.tsx": {
    id: "features/login/route";
    page: "/login";
  };
  "features/execution/route.tsx": {
    id: "features/execution/route";
    page: "/execution";
  };
  "features/media-prices/route.tsx": {
    id: "features/media-prices/route";
    page: "/media-prices";
  };
  "features/quotations/route.tsx": {
    id: "features/quotations/route";
    page: "/quotations";
  };
  "features/onboarding/route.tsx": {
    id: "features/onboarding/route";
    page: "/onboarding";
  };
  "features/services/service-visibility/route.tsx": {
    id: "features/services/service-visibility/route";
    page: "/service-visibility";
  };
  "features/services/service-risk/route.tsx": {
    id: "features/services/service-risk/route";
    page: "/service-risk";
  };
  "features/services/service-site-audit/route.tsx": {
    id: "features/services/service-site-audit/route";
    page: "/service-site-audit";
  };
  "features/services/service-pilot/route.tsx": {
    id: "features/services/service-pilot/route";
    page: "/service-pilot";
  };
  "features/services/formal-reports/route.tsx": {
    id: "features/services/formal-reports/route";
    page: "/formal-reports";
  };
  "features/sop/route.tsx": {
    id: "features/sop/route";
    page: "/sop";
  };
  "features/sop/project-route.tsx": {
    id: "features/sop/project-route";
    page: "/sop/projects/:projectPubId";
  };
  "features/post-analysis/route.tsx": {
    id: "features/post-analysis/route";
    page: "/post-analysis";
  };
  "features/post-analysis/task-route.tsx": {
    id: "features/post-analysis/task-route";
    page: "/post-analysis/tasks/:taskPubId";
  };
  "features/account-governance/accounts-route.tsx": {
    id: "features/account-governance/accounts-route";
    page: "/accounts";
  };
  "features/account-governance/browsers-route.tsx": {
    id: "features/account-governance/browsers-route";
    page: "/browsers";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "shell": typeof import("./app/shell.tsx");
  "features/login/route": typeof import("./app/features/login/route.tsx");
  "features/execution/route": typeof import("./app/features/execution/route.tsx");
  "features/media-prices/route": typeof import("./app/features/media-prices/route.tsx");
  "features/quotations/route": typeof import("./app/features/quotations/route.tsx");
  "features/onboarding/route": typeof import("./app/features/onboarding/route.tsx");
  "features/services/service-visibility/route": typeof import("./app/features/services/service-visibility/route.tsx");
  "features/services/service-risk/route": typeof import("./app/features/services/service-risk/route.tsx");
  "features/services/service-site-audit/route": typeof import("./app/features/services/service-site-audit/route.tsx");
  "features/services/service-pilot/route": typeof import("./app/features/services/service-pilot/route.tsx");
  "features/services/formal-reports/route": typeof import("./app/features/services/formal-reports/route.tsx");
  "features/sop/route": typeof import("./app/features/sop/route.tsx");
  "features/sop/project-route": typeof import("./app/features/sop/project-route.tsx");
  "features/post-analysis/route": typeof import("./app/features/post-analysis/route.tsx");
  "features/post-analysis/task-route": typeof import("./app/features/post-analysis/task-route.tsx");
  "features/account-governance/accounts-route": typeof import("./app/features/account-governance/accounts-route.tsx");
  "features/account-governance/browsers-route": typeof import("./app/features/account-governance/browsers-route.tsx");
};