// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/execution": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/execution";
  };
  "shell.tsx": {
    id: "shell";
    page: "/";
  };
  "features/execution/route.tsx": {
    id: "features/execution/route";
    page: "/execution";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "shell": typeof import("./app/shell.tsx");
  "features/execution/route": typeof import("./app/features/execution/route.tsx");
};