// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/experience-states": {
    params: {};
  };
  "/experience-performance": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/experience-states" | "/experience-performance";
  };
  "shell.tsx": {
    id: "shell";
    page: "/";
  };
  "state-matrix.tsx": {
    id: "state-matrix";
    page: "/experience-states";
  };
  "performance-matrix.tsx": {
    id: "performance-matrix";
    page: "/experience-performance";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "shell": typeof import("./app/shell.tsx");
  "state-matrix": typeof import("./app/state-matrix.tsx");
  "performance-matrix": typeof import("./app/performance-matrix.tsx");
};